### PR TITLE
#2: New things and bugs

### PR DESCRIPTION
**Pull request by edikxl**
I've create a music manager. BUT it doesn't work as I want. I've had a few problems:
Firstly, webpack. I understand that it is useful and powerfull tool, but it's too hard for your game.
I hate this system of loaders. You cannot use just files such a music or photos in usual way ( and, I quess, you know about it, because I've read your code and you use data:base64 for textures ). All we need performance sometimes, I understand. But there appears a problem that I haven't solved - wrong media type( Media error 4 ). Webpach rewrites mp3 files to configs where are a directory of a real files and other info and audio element doesn't understand where is a music. It was such a hard night. I'm sorry if I look angry or sad. It was really fun for me.
So. You have music system, but you cannot listen to music. I thought not to contribute, but if you will try to fix all these strange things, it's easier to start from something. Thank you for the experience.

### CODE REVIEW

**Comment by sarcoma** [comment]
Nice work, thank for all the hard work. I'm so sorry about the Webpack issues, the dependencies were woefully out of date. I've updated the packages and added and index.js file to the music folder. 

I'd typically add an AWS file manager to Webpack to move the image and audio files off to storage on build, but that's a long way off. 

Thanks again, good job.

**Comment by sarcoma** [comment]
It's working on the github.io site now: https://sarcoma.github.io/Drone-Squadron-JS-V3ish/dist/

**Comment by edikxl** [comment]
Your solution is really great. It's much more easier than things that I've done. Thank you for meeting with webpack. I glad to help OpenSource!

**Comment by sarcoma** [comment]
Thanks for the PR! So kind of you to donate your time to the project/

**Pull request merged**
